export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REG_REQUEST = "REG_REQUEST";
export const REG_SUCCESS = "REG_SUCCESS";
export const REG_FAILURE = "REG_FAILURE";

export const GET_USER_REQ = "GET_USER_REQ";
export const GET_USER_SUCCC = "GET_USER_SUCC";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const RESTORE_AUTH = "RESTORE_AUTH";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const TASK_REQUEST = "TASK_REQUEST";
export const TASK_SUCCESS = "TASK_SUCCESS";
export const TASK_FAIL = "TASK_FAIL";

export const TASK_GET_REQ = "TASK_GET_REQ";
export const TASK_GET_SUCC = "TASK_GET_SUCC";
export const TASK_GET_FAIL = "TASK_GET_FAIL";

export const TASK_DEL_REQ = "TASK_DEL_REQ";
export const TASK_DEL_SUCC = "TASK_DEL_SUCC";
export const TASK_DEL_FAIL = "TASK_DEL_FAIL";

export const TASK_EDIT_REQ = "TASK_EDIT_REQ";
export const TASK_EDIT_SUCC = "TASK_EDIT_SUCC";
export const TASK_EDIT_FAIL = "TASK_EDIT_FAIL";


export const UPDATE_TASK_COMPLETION_REQUEST = "UPDATE_TASK_COMPLETION_REQUEST"
export const UPDATE_TASK_COMPLETION_SUCCESS = "UPDATE_TASK_COMPLETION_SUCCESS"
export const  UPDATE_TASK_COMPLETION_FAILURE = "UPDATE_TASK_COMPLETION_FAILURE"
